### ISSUE TITLE
Inclusion of version= label in all metrics

### ISSUE THREAD

**Issue by andrebreves** [labbsr0x/bb-protocol#4]
We have the need to compare the performance between different version of the application, sometimes running in parallel (but not always).

We achieved this comparison by including the version of the application in all metrics.

**Comment by eabili0** [comment]
@andrebreves, please take a look at this issue https://github.com/labbsr0x/big-brother/issues/12

The `version` label was removed to be replaced by the `application_info` metric. There are some good reasons for that in this post: https://www.robustperception.io/exposing-the-software-version-to-prometheus

**Comment by andrebreves** [comment]
And what connects a value of the metric to a specific `application_info` time serie?

On the linked article it seems that the `instance` and `job` labels are used to do link the metrics. Is that correct?

**Comment by andrebreves** [comment]
> On the linked article it seems that the `instance` label is used to do link the metrics.

By [this documentation](https://prometheus.io/docs/concepts/jobs_instances/) both `job` and `instance` labels don't seem to be unique.

**Comment by eabili0** [comment]
@andrebreves, you can join any metric to the `application_info` using the `or` operator grouping by `instance`, for example.

**Comment by eabili0** [comment]
And I agree, we have to be careful with the `instance` label. If it is not unique, you'll not only have problems with this scenario but a whole bunch of other scenarios as well.

**Comment by eabili0** [comment]
I would add that to make it really unique, you should always combine `instance` with `job`. So, you could have a scenario where you have a metric `requests_seconds_count` and want to query it's values from version `1.0.1`. To do that, you could:

`sum(requests_seconds_count and application_info{version='1.0.1'}) by (instance, job)`

**Comment by eabili0** [comment]
@KarineValenca, could you please provide examples of how this is being used to create real alerting rules? Thanks!

**Comment by KarineValenca** [comment]
@andrebreves In this [file](https://github.com/labbsr0x/bb-promster/blob/master/alert_rules/alert-rules.yml.tmpl), you can find some examples of how to combine `application_info` with other metrics. Also, this file contains some examples of comparative alerts between versions. 

But there is a simple example:
```
request_duration_seconds_count 
and ignoring(addr) sum by(instance, prsn) (application_info{version="1.0.1"})) 
 / 
ignoring(instance) (request_duration_seconds_count
and ignoring(addr) sum by(instance, prsn) (application_info{version="1.0.0"})) 
```

This rule compares counters for each addr between version 1.0.1 and version 1.0.0

**Comment by eabili0** [comment]
@andrebreves, I'll be closing this issue for now. If you have any further doubts, fell free to comment on this issue. Thank you!
